import Image from 'next/image';
import { cn } from '@/lib/utils';

/**
 * KP Rück brand mark (the Magnettafel on the ink tile). Generated by scripts/build-icons.mjs —
 * the same artwork as the app icon, so the login matches the home screen. Decorative: it always
 * stands next to the «KP Rück» wordmark, hence the empty alt.
 */
export function BrandMark({ size = 56, className }: { size?: number; className?: string }) {
  return (
    <Image
      src="/icons/mark.svg"
      alt=""
      width={size}
      height={size}
      priority
      unoptimized
      className={cn('shrink-0 select-none', className)}
    />
  );
}
