"""CRUD for the `/feld` field surface (plans 25 and 26).

Two things live here, and the second one is the load-bearing part:

1. The read queries behind the person picker and "meine Einsatzstellen".
2. **Step 2 of the `/feld` authorization.** The event token (step 1) only says
   *which Ereignis*; it never says *who*. Visibility is "only mine" (decision 4)
   and it is enforced here, server-side, never in the UI.

Since plan 26 "mine" is a **union of four sources** — crew, reko, driver,
magazin — because a driver holds no personnel row at all and a Magazin person is
assigned to nothing. The rule, its precedence, and which sources may write what
live in ``visibility.py``; read that module's docstring before touching any of
it.

Every endpoint mounts on ``person_has_event_access`` / ``get_authorized_incident``;
adding one without either is the hole this package exists to prevent.
"""

# Split from a single 2300-line module (plan 26, decision 21). The package
# re-exports every name the old module exposed, so `from ..crud import feld`
# and `crud.<anything>` keep working unchanged — including the underscore
# helpers the tests reach for.

from .access import (
    claim_is_live,
    code_matches,
    create_claim,
    generate_code,
    is_checked_in,
    live_device_count,
    regenerate_code,
    revoke_all_claims,
)
from .material import (
    apply_material_decisions,
    event_restliste,
    material_left_on_site_named,
    material_overview,
    material_return_attribution,
    material_return_units,
)
from .melden import (
    EDITABLE_STATUS,
    create_field_report,
    own_reports,
    report_is_editable,
    report_summary,
    update_field_report,
)
from .rapport import (
    CONCURRENT_EDITOR_WINDOW,
    _board_material_units,
    _board_personnel_count,
    _build_cost_snapshot,
    _concurrent_editor,
    _event_personnel,
    _fleet_vehicles,
    _is_answered,
    _jsonable_materials,
    _jsonable_personnel,
    _jsonable_vehicles,
    _material_name_suggestions,
    _material_used,
    _names,
    _route_assigned_ids,
    add_photo,
    derive_personnel_count,
    get_rapport,
    normalize_extra_materials,
    normalize_extra_personnel,
    reconcile_materials,
    reconcile_personnel,
    reconcile_vehicles,
    remove_photo,
    save_rapport,
)
from .reports import (
    FieldActor,
    _broadcast,
    _get_or_create_report,
    _location,
    _stamp_updated_by,
    field_report_state,
    is_automation_user,
    record_arrival,
    record_field_complete,
    record_field_message,
    record_pickup,
)
from .visibility import (
    _DANGER_KEYS,
    ARRIVAL_SOURCES,
    RAPPORT_SOURCES,
    SOURCE_CREW,
    SOURCE_DRIVER,
    SOURCE_MAGAZIN,
    SOURCE_PRECEDENCE,
    SOURCE_REKO,
    WORK_SOURCES,
    FeldSource,
    _briefings,
    _event_incidents,
    _rapport_state,
    _rapport_states,
    _reko_briefings,
    driver_vehicle_names,
    functions_for_personnel,
    get_authorized_incident,
    get_feld_assignments_for_personnel,
    get_feld_personnel_for_event,
    get_incident_leaders,
    person_has_event_access,
    visible_by_personnel,
    visible_incidents_for_personnel,
)

__all__ = [
    "ARRIVAL_SOURCES",
    "CONCURRENT_EDITOR_WINDOW",
    "EDITABLE_STATUS",
    "RAPPORT_SOURCES",
    "SOURCE_CREW",
    "SOURCE_DRIVER",
    "SOURCE_MAGAZIN",
    "SOURCE_PRECEDENCE",
    "SOURCE_REKO",
    "WORK_SOURCES",
    "_DANGER_KEYS",
    "FeldSource",
    "FieldActor",
    "_board_material_units",
    "_board_personnel_count",
    "_briefings",
    "_broadcast",
    "_build_cost_snapshot",
    "_concurrent_editor",
    "_event_incidents",
    "_event_personnel",
    "_fleet_vehicles",
    "_get_or_create_report",
    "_is_answered",
    "_jsonable_materials",
    "_jsonable_personnel",
    "_jsonable_vehicles",
    "_location",
    "_material_name_suggestions",
    "_material_used",
    "_names",
    "_rapport_state",
    "_rapport_states",
    "_reko_briefings",
    "_route_assigned_ids",
    "_stamp_updated_by",
    "add_photo",
    "apply_material_decisions",
    "claim_is_live",
    "code_matches",
    "create_claim",
    "create_field_report",
    "derive_personnel_count",
    "driver_vehicle_names",
    "event_restliste",
    "field_report_state",
    "functions_for_personnel",
    "generate_code",
    "get_authorized_incident",
    "get_feld_assignments_for_personnel",
    "get_feld_personnel_for_event",
    "get_incident_leaders",
    "get_rapport",
    "is_automation_user",
    "is_checked_in",
    "live_device_count",
    "material_left_on_site_named",
    "material_overview",
    "material_return_attribution",
    "material_return_units",
    "normalize_extra_materials",
    "normalize_extra_personnel",
    "own_reports",
    "person_has_event_access",
    "reconcile_materials",
    "reconcile_personnel",
    "reconcile_vehicles",
    "record_arrival",
    "record_field_complete",
    "record_field_message",
    "record_pickup",
    "regenerate_code",
    "remove_photo",
    "report_is_editable",
    "report_summary",
    "revoke_all_claims",
    "save_rapport",
    "update_field_report",
    "visible_by_personnel",
    "visible_incidents_for_personnel",
]
