import type { Metadata, Viewport } from 'next'
import localFont from 'next/font/local'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages, getTranslations } from 'next-intl/server'
import { cookies } from 'next/headers'
import { BootCover } from '@/components/boot-cover'
import { SNAIL_STANDING_COOKIE } from '@/lib/snail-clock'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { AuthProvider } from '@/lib/contexts/auth-context'
import { EventProvider } from '@/lib/contexts/event-context'
import { PersonnelProvider } from '@/lib/contexts/personnel-context'
import { MaterialsProvider } from '@/lib/contexts/materials-context'
import { OperationsProvider } from '@/lib/contexts/operations-context'
import { GroupsProvider } from '@/lib/contexts/groups-context'
import { NotificationProvider } from '@/lib/contexts/notification-context'
import { CommandPaletteProvider } from '@/lib/contexts/command-palette-context'
import { NotificationToasts } from '@/components/notifications/notification-toasts'
import { DismissAllToasts } from '@/components/ui/sonner'
import { AppShell } from '@/components/app-shell'
import { VehicleDriverPrompt } from '@/components/vehicle-driver-prompt'
import { ResourceConflictPrompt } from '@/components/resource-conflict-prompt'
import { GpsReleasePrompt } from '@/components/gps-release-prompt'
import { GpsArrivalPrompt } from '@/components/gps-arrival-prompt'
import { PickupDonePrompt } from '@/components/pickup-done-prompt'
import { ErrorReporter } from '@/components/error-reporter'
import { RuntimeBackendOrigin } from '@/components/runtime-backend-origin'
import { publicBackendOrigin } from '@/lib/env'
import { TopLoadingBar } from '@/components/ui/top-loading-bar'
import { ViewportInsets } from '@/components/viewport-insets'
import { ThemeColorSync } from '@/components/theme-color-sync'
import { THEME_COLOR } from '@/lib/theme-color'

// Sora + Spline Sans Mono — the same faces as KP Front and kp-rueck.ch, so the
// two apps and the site read as one family. Self-hosted (variable woff2, Latin
// subset, SIL OFL 1.1 — licences next to the files): a station that runs
// offline must not depend on a font CDN, and next/font/google fetches at build
// time. The variables feed `--font-sans` / `--font-mono` in globals.css.
const sora = localFont({
  src: [{ path: './fonts/sora.woff2', weight: '100 800', style: 'normal' }],
  display: 'swap',
  variable: '--font-sora',
})

const splineSansMono = localFont({
  src: [{ path: './fonts/spline-sans-mono.woff2', weight: '300 700', style: 'normal' }],
  display: 'swap',
  variable: '--font-spline-sans-mono',
  fallback: ['Courier New', 'monospace'],
})

/**
 * The system bars take the page's own background per scheme (lib/theme-color.ts): on the iOS
 * home-screen app that is the status-bar strip above the first row — solid, instead of iOS's
 * frosted fallback for a page that declares no colour. `ThemeColorSync` corrects it when the user
 * picked a scheme other than the phone's.
 */
export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: THEME_COLOR.light },
    { media: '(prefers-color-scheme: dark)', color: THEME_COLOR.dark },
  ],
}

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations('common.meta')
  return {
    title: t('title'),
    description: t('description'),
    // All generated by scripts/build-icons.mjs. The apple-touch-icon MUST be a PNG: iOS ignores
    // an SVG there and puts a screenshot of the page on the home screen instead.
    icons: {
      icon: [{ url: '/icon.svg', type: 'image/svg+xml' }],
      shortcut: '/icon.svg',
      apple: [{ url: '/icons/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
    },
    // The home-screen label; the page title («KP Rück Dashboard») would be cut off.
    // `default`, said out loud: the web view starts below the status bar and the bar takes the
    // theme-color above. `black-translucent` (content under the bar) is ignored since iOS 26.1.
    appleWebApp: { title: 'KP Rück', statusBarStyle: 'default' },
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  const messages = await getMessages()
  // Set for a few seconds by the Microsoft callback right before it loads the app: the boot
  // snail of THIS document continues that one, so it must not paint at its arrival's first
  // frame (lib/snail-clock.ts).
  const snailStanding = (await cookies()).get(SNAIL_STANDING_COOKIE)?.value === 'standing'

  return (
    <html lang={locale} suppressHydrationWarning data-snail={snailStanding ? 'standing' : undefined}>
      <body className={`${sora.variable} ${splineSansMono.variable} font-sans antialiased`}>
        {/* Where the browser may open its WebSocket. Read here because API_URL is a RUNTIME
            variable — the same one the /backend-api proxy route uses — and this layout renders
            per request. Null on a deployment that sits behind one origin (compose/Caddy) or
            names the backend only inside a container network; getWsUrl() then falls back to
            the behaviour it always had. */}
        <RuntimeBackendOrigin
          origin={publicBackendOrigin(process.env.API_URL)}
          cartoApiKey={process.env.CARTO_API_KEY?.trim() || null}
        />
        <TopLoadingBar />
        {/* --kb-inset / --vv-height on <html>: the on-screen keyboard, for the phone sheets. */}
        <ViewportInsets />
        {/* Catches what escapes the React tree (rejected promises, listeners) and posts
            it to this station's OWN server log. Opt-in forwarding is a separate decision
            made server-side — see lib/report-error.ts. */}
        <ErrorReporter />
        <NextIntlClientProvider locale={locale} messages={messages}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeColorSync />
          {/* A launch opens behind the snail: over everything until the workspace is usable. */}
          <BootCover />
          <AuthProvider>
            <EventProvider>
              <PersonnelProvider>
                <MaterialsProvider>
                  <OperationsProvider>
                    <GroupsProvider>
                      <NotificationProvider>
                        <CommandPaletteProvider>
                          <AppShell>
                            {children}
                          </AppShell>
                          <NotificationToasts />
                          <DismissAllToasts />
                          <VehicleDriverPrompt />
                          <ResourceConflictPrompt />
                          <GpsReleasePrompt />
                          <GpsArrivalPrompt />
                          <PickupDonePrompt />
                        </CommandPaletteProvider>
                      </NotificationProvider>
                    </GroupsProvider>
                  </OperationsProvider>
                </MaterialsProvider>
              </PersonnelProvider>
            </EventProvider>
          </AuthProvider>
        </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
