import type { MetadataRoute } from 'next'

// The web app manifest, served by Next at /manifest.webmanifest (and linked from every page).
// Without it Android offers no installable app and iOS has no name or icon to fall back on.
// The icons are generated by scripts/build-icons.mjs — the one place the artwork lives.
//
// Static German, like KP Front's: it is read once, when someone adds the app to a home screen,
// before any locale is known. `display: 'standalone'` means the home-screen app opens without
// the browser's address bar — and on iOS with its own storage, so a crew member logs in once
// more after adding it.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'KP Rück',
    short_name: 'KP Rück',
    description: 'Einsatzübersicht für die Mannschafts- und Materialdisposition der Feuerwehr.',
    lang: 'de-CH',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    theme_color: '#1b2330',
    background_color: '#1b2330',
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  }
}
