"""Add display_order and radio_call_sign to vehicles, type and description to materials

Revision ID: 15f9942dbb87
Revises: cbd35b46565b
Create Date: 2025-10-26 19:09:05.864081

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15f9942dbb87"
down_revision: str | Sequence[str] | None = "cbd35b46565b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_event_attendance_event_id"), "event_attendance", ["event_id"], unique=False)
    op.create_index(op.f("ix_event_attendance_personnel_id"), "event_attendance", ["personnel_id"], unique=False)

    # Add materials columns with defaults for existing data
    op.add_column("materials", sa.Column("type", sa.String(length=50), nullable=True))
    op.add_column("materials", sa.Column("description", sa.Text(), nullable=True))

    # Update existing materials rows with default type
    op.execute("UPDATE materials SET type = 'Sonstiges' WHERE type IS NULL")

    # Now make type NOT NULL
    op.alter_column("materials", "type", nullable=False)

    # Make location NOT NULL
    op.alter_column("materials", "location", existing_type=sa.VARCHAR(length=255), nullable=False)

    # Add vehicles columns with defaults for existing data
    op.add_column("vehicles", sa.Column("display_order", sa.Integer(), nullable=True))
    op.add_column("vehicles", sa.Column("radio_call_sign", sa.String(length=100), nullable=True))

    # Update existing vehicles rows with default values
    # Set display_order based on current row order (assign sequential numbers)
    op.execute("""
        UPDATE vehicles
        SET display_order = subquery.row_num
        FROM (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) as row_num
            FROM vehicles
        ) as subquery
        WHERE vehicles.id = subquery.id
    """)

    # Set default radio_call_sign based on name
    op.execute("UPDATE vehicles SET radio_call_sign = name WHERE radio_call_sign IS NULL")

    # Now make them NOT NULL
    op.alter_column("vehicles", "display_order", nullable=False)
    op.alter_column("vehicles", "radio_call_sign", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicles", "radio_call_sign")
    op.drop_column("vehicles", "display_order")
    op.alter_column("materials", "location", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_column("materials", "description")
    op.drop_column("materials", "type")
    op.drop_index(op.f("ix_event_attendance_personnel_id"), table_name="event_attendance")
    op.drop_index(op.f("ix_event_attendance_event_id"), table_name="event_attendance")
    # ### end Alembic commands ###
