"""Add display_order and radio_call_sign to vehicles, type and description to materials

Revision ID: 15f9942dbb87
Revises: cbd35b46565b
Create Date: 2025-10-26 19:09:05.864081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f9942dbb87'
down_revision: Union[str, Sequence[str], None] = 'cbd35b46565b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_attendance_event_id'), 'event_attendance', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_attendance_personnel_id'), 'event_attendance', ['personnel_id'], unique=False)
    op.add_column('materials', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('materials', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('materials', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('vehicles', sa.Column('display_order', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('radio_call_sign', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'radio_call_sign')
    op.drop_column('vehicles', 'display_order')
    op.alter_column('materials', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('materials', 'description')
    op.drop_column('materials', 'type')
    op.drop_index(op.f('ix_event_attendance_personnel_id'), table_name='event_attendance')
    op.drop_index(op.f('ix_event_attendance_event_id'), table_name='event_attendance')
    # ### end Alembic commands ###
