"""Initial schema with all tables

Revision ID: 880ce6c5ec4d
Revises: 
Create Date: 2025-10-23 22:00:37.855212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '880ce6c5ec4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('editor', 'viewer')", name='valid_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'assigned', 'maintenance')", name='valid_vehicle_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('changes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_resource', 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('idx_audit_user', 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('location_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('training_flag', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name='valid_priority'),
    sa.CheckConstraint("status IN ('eingegangen', 'reko', 'disponiert', 'einsatz', 'einsatz_beendet', 'abschluss')", name='valid_status'),
    sa.CheckConstraint('(location_lat IS NULL AND location_lng IS NULL) OR (location_lat IS NOT NULL AND location_lng IS NOT NULL)', name='valid_location'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('incident_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("resource_type IN ('personnel', 'vehicle', 'material')", name='valid_resource_type'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'resource_type', 'resource_id', 'unassigned_at', name='unique_assignment')
    )
    op.create_index('idx_assignments_incident', 'incident_assignments', ['incident_id'], unique=False)
    op.create_index('idx_assignments_resource', 'incident_assignments', ['resource_type', 'resource_id'], unique=False)
    op.create_table('reko_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('dangers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effort_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('power_supply', sa.String(length=50), nullable=True),
    sa.Column('photos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('submitted_by_token', sa.String(length=255), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reko_incident', 'reko_reports', ['incident_id'], unique=False)
    op.create_index('idx_reko_token', 'reko_reports', ['token'], unique=False)
    op.create_table('status_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=False),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transitions_incident', 'status_transitions', ['incident_id'], unique=False)

    # Drop old tables that need schema changes (if they exist)
    op.drop_index(op.f('ix_operations_id'), table_name='operations', if_exists=True)
    op.drop_table('operations', if_exists=True)
    op.drop_index(op.f('ix_materials_id'), table_name='materials', if_exists=True)
    op.drop_table('materials', if_exists=True)
    op.drop_index(op.f('ix_personnel_id'), table_name='personnel', if_exists=True)
    op.drop_table('personnel', if_exists=True)

    # Recreate materials table with new schema
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'assigned', 'maintenance')", name='valid_material_status'),
    sa.PrimaryKeyConstraint('id')
    )

    # Recreate personnel table with new schema
    op.create_table('personnel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability IN ('available', 'assigned', 'unavailable')", name='valid_personnel_availability'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop new tables and recreate old ones
    op.drop_table('personnel')
    op.drop_table('materials')

    # Recreate old materials table
    op.create_table('materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('materials_pkey'))
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)

    # Recreate old personnel table
    op.create_table('personnel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('personnel_pkey'))
    )
    op.create_index(op.f('ix_personnel_id'), 'personnel', ['id'], unique=False)

    op.create_table('operations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vehicle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('incident_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dispatch_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('crew', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('coordinates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('materials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contact', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('operations_pkey'))
    )
    op.create_index(op.f('ix_operations_id'), 'operations', ['id'], unique=False)
    op.drop_index('idx_transitions_incident', table_name='status_transitions')
    op.drop_table('status_transitions')
    op.drop_index('idx_reko_token', table_name='reko_reports')
    op.drop_index('idx_reko_incident', table_name='reko_reports')
    op.drop_table('reko_reports')
    op.drop_index('idx_assignments_resource', table_name='incident_assignments')
    op.drop_index('idx_assignments_incident', table_name='incident_assignments')
    op.drop_table('incident_assignments')
    op.drop_table('settings')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index('idx_audit_user', table_name='audit_log')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_resource', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
