"""remove_priority_from_divera_emergencies

Revision ID: 94803763b5de
Revises: b42d9c6f8bb7
Create Date: 2025-12-03 11:28:13.331949

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94803763b5de"
down_revision: str | Sequence[str] | None = "b42d9c6f8bb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("divera_emergencies", "priority")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "divera_emergencies",
        sa.Column("priority", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
