"""add_submitted_by_personnel_id_to_reko_reports

Revision ID: b42d9c6f8bb7
Revises: e0f2105b967e
Create Date: 2025-12-02 22:21:29.082114

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b42d9c6f8bb7"
down_revision: str | Sequence[str] | None = "e0f2105b967e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reko_reports", sa.Column("submitted_by_personnel_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "reko_reports", "personnel", ["submitted_by_personnel_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reko_reports", type_="foreignkey")
    op.drop_column("reko_reports", "submitted_by_personnel_id")
    # ### end Alembic commands ###
