"""add event_attendance table for event-specific check-ins

Revision ID: cbd35b46565b
Revises: 06b032721f70
Create Date: 2025-10-25 22:40:21.456126

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbd35b46565b"
down_revision: str | Sequence[str] | None = "06b032721f70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create event_attendance table for event-specific check-ins
    op.create_table(
        "event_attendance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("personnel_id", sa.UUID(), nullable=False),
        sa.Column("checked_in", sa.Boolean(), nullable=False),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "personnel_id", name="unique_event_personnel_attendance"),
    )
    op.create_index("idx_event_attendance_event", "event_attendance", ["event_id"])
    op.create_index("idx_event_attendance_personnel", "event_attendance", ["personnel_id"])
    op.create_index("idx_event_attendance_checked_in", "event_attendance", ["event_id", "checked_in"])

    # Clean up other schema changes
    op.drop_index(op.f("ix_events_archived_at"), table_name="events")
    op.drop_index(op.f("ix_events_last_activity_at"), table_name="events")
    op.drop_column("materials", "type")
    op.create_index(op.f("ix_personnel_checked_in"), "personnel", ["checked_in"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse other schema changes
    op.drop_index(op.f("ix_personnel_checked_in"), table_name="personnel")
    op.add_column("materials", sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f("ix_events_last_activity_at"), "events", ["last_activity_at"], unique=False)
    op.create_index(op.f("ix_events_archived_at"), "events", ["archived_at"], unique=False)

    # Drop event_attendance table
    op.drop_index("idx_event_attendance_checked_in", table_name="event_attendance")
    op.drop_index("idx_event_attendance_personnel", table_name="event_attendance")
    op.drop_index("idx_event_attendance_event", table_name="event_attendance")
    op.drop_table("event_attendance")
    # ### end Alembic commands ###
