"""add contact and internal_notes to incidents

Revision ID: e0f2105b967e
Revises: 79c6490d57fc
Create Date: 2025-12-02 21:58:30.740592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f2105b967e'
down_revision: Union[str, Sequence[str], None] = '79c6490d57fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('divera_emergencies_divera_id_key'), 'divera_emergencies', type_='unique')
    op.create_index(op.f('ix_divera_emergencies_attached_to_event_id'), 'divera_emergencies', ['attached_to_event_id'], unique=False)
    op.create_index(op.f('ix_divera_emergencies_divera_id'), 'divera_emergencies', ['divera_id'], unique=True)
    op.create_index(op.f('ix_divera_emergencies_is_archived'), 'divera_emergencies', ['is_archived'], unique=False)
    op.create_index(op.f('ix_divera_emergencies_received_at'), 'divera_emergencies', ['received_at'], unique=False)
    op.create_index(op.f('ix_event_special_functions_event_id'), 'event_special_functions', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_special_functions_personnel_id'), 'event_special_functions', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_event_special_functions_vehicle_id'), 'event_special_functions', ['vehicle_id'], unique=False)
    op.create_index('idx_assignments_resource_id', 'incident_assignments', ['resource_id'], unique=False)
    op.create_index('idx_assignments_unassigned', 'incident_assignments', ['unassigned_at'], unique=False)
    op.add_column('incidents', sa.Column('contact', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('internal_notes', sa.Text(), nullable=True))
    op.create_index('idx_incidents_created_at', 'incidents', ['created_at'], unique=False)
    op.create_index('idx_incidents_event_status_deleted', 'incidents', ['event_id', 'status', 'deleted_at'], unique=False)
    op.create_index('idx_incidents_priority', 'incidents', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_incidents_priority', table_name='incidents')
    op.drop_index('idx_incidents_event_status_deleted', table_name='incidents')
    op.drop_index('idx_incidents_created_at', table_name='incidents')
    op.drop_column('incidents', 'internal_notes')
    op.drop_column('incidents', 'contact')
    op.drop_index('idx_assignments_unassigned', table_name='incident_assignments')
    op.drop_index('idx_assignments_resource_id', table_name='incident_assignments')
    op.drop_index(op.f('ix_event_special_functions_vehicle_id'), table_name='event_special_functions')
    op.drop_index(op.f('ix_event_special_functions_personnel_id'), table_name='event_special_functions')
    op.drop_index(op.f('ix_event_special_functions_event_id'), table_name='event_special_functions')
    op.drop_index(op.f('ix_divera_emergencies_received_at'), table_name='divera_emergencies')
    op.drop_index(op.f('ix_divera_emergencies_is_archived'), table_name='divera_emergencies')
    op.drop_index(op.f('ix_divera_emergencies_divera_id'), table_name='divera_emergencies')
    op.drop_index(op.f('ix_divera_emergencies_attached_to_event_id'), table_name='divera_emergencies')
    op.create_unique_constraint(op.f('divera_emergencies_divera_id_key'), 'divera_emergencies', ['divera_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
