"""Increase reko token column size to 500

Revision ID: e99d83752bc8
Revises: 436a11d28487
Create Date: 2025-11-01 23:07:51.297923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99d83752bc8'
down_revision: Union[str, Sequence[str], None] = '436a11d28487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_assignments_resource_lookup'), table_name='incident_assignments')
    op.drop_index(op.f('idx_incidents_event_status_deleted'), table_name='incidents')
    op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=False)
    op.create_index(op.f('ix_notifications_incident_id'), 'notifications', ['incident_id'], unique=False)
    op.alter_column('reko_reports', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index(op.f('idx_status_transitions_incident_timestamp'), table_name='status_transitions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_status_transitions_incident_timestamp'), 'status_transitions', ['incident_id', sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('reko_reports', 'token',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_incident_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
    op.create_index(op.f('idx_incidents_event_status_deleted'), 'incidents', ['event_id', 'status', 'deleted_at'], unique=False)
    op.create_index(op.f('idx_assignments_resource_lookup'), 'incident_assignments', ['resource_type', 'resource_id', 'unassigned_at'], unique=False)
    # ### end Alembic commands ###
