import type { MetadataRoute } from 'next'

import {
  AVAILABLE_LOCALES,
  DEFAULT_LOCALE,
  isSupportedLocale,
  loadMessages,
  type SupportedLocale,
} from '@/lib/i18n-messages'

// The web app manifest, served at /manifest.webmanifest (app/manifest.webmanifest/route.ts)
// and linked from every page by the root layout. Without it Android offers no installable app
// and iOS has no name or icon to fall back on. The icons are generated by
// scripts/build-icons.mjs — the one place the artwork lives.
//
// In the device's language: the layout links `/manifest.webmanifest?lang=<locale>`, because a
// browser fetches the manifest WITHOUT cookies (no `crossorigin="use-credentials"` on the link),
// so the NEXT_LOCALE cookie never reaches it — the link has to say it. Only a locale the
// language picker offers (AVAILABLE_LOCALES) is honoured: Italian is not complete yet, and an
// installed app announcing `it-CH` over German text would be a lie. Everything else is German.
//
// `display: 'standalone'` means the home-screen app opens without the browser's address bar —
// and on iOS with its own storage, so a crew member logs in once more after adding it.

/** The locale a manifest request asked for, narrowed to what actually ships. */
export function manifestLocale(requested: string | null | undefined): SupportedLocale {
  const locale = requested ?? undefined
  return isSupportedLocale(locale) && AVAILABLE_LOCALES.includes(locale) ? locale : DEFAULT_LOCALE
}

export function buildManifest(locale: SupportedLocale = DEFAULT_LOCALE): MetadataRoute.Manifest {
  return {
    name: 'KP Rück',
    short_name: 'KP Rück',
    description: loadMessages(locale).common.meta.description,
    lang: `${locale}-CH`,
    start_url: '/',
    scope: '/',
    display: 'standalone',
    theme_color: '#1b2330',
    background_color: '#1b2330',
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  }
}
